Fix Gradle coordinate comparison
When two Gradle coordinates were being compared, and they a different number
of version numbers yet agreed in values for the values they do share, the
comparators would crash with
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3 in java.util.ArrayList

(User reported crash.)

Change-Id: Ic7e926ae6e3ffa4401a1f4a2e0b8bea21b895597
(cherry picked from commit 1146e502d254b9b92f7b9b14cd5e0a3c5f778196)